force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Book Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/Borrowing_Record__c.object-meta.xml
<CustomObject>
    <label>Borrowing Record</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Borrowing Record id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Status__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Status__c</fullName>
    <label>Borrow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PreventBookDeleteHandler.cls
public with sharing class PreventBookDeleteHandler {

    public static void PreventBookDelete(List<Book__c> bookList) {

        
            set<Id> bookId = new set<Id>();

            for(Book__c b : bookList)
            {
                bookId.add(b.Id);
            }

            List<Borrowing_Record__c> activeBorrows = [SELECT Id, Book__c FROM Borrowing_Record__c WHERE Book__c IN :bookId AND Borrow_Status__c = 'Borrowed'];
            set<Id> activeBookId = new Set<Id>();

            for(Borrowing_Record__c br : activeBorrows)
            {
                activeBookId.add(br.Book__c);
            }

            for(Book__c b : bookList)
            {
                if(activeBookId.contains(b.Id))
                {
                    b.addError('Cannot delete book as it is currently borrowed');
                }
            }

    }
}