force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Book Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fiction</fullName>
            </value>
            <value>
                <fullName>Non-Fiction</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>&apos;Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/Borrowing_Record__c.object-meta.xml
<CustomObject>
    <label>Borrowing Record</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Borrowing Record id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Date__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Date__c</fullName>
    <label>Borrow Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Status__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Status__c</fullName>
    <label>Borrow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Is_Returned__c.field-meta.xml
<CustomField>
    <fullName>Is_Returned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Returned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <description>Related Member Name</description>
    <label>Member Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Borrow_Count__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Count__c</fullName>
    <label>Borrow Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <label>Member Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Librarian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LibraryController.cls
public with sharing class LibraryController {


// ------------------- GET BOOKS -------------------
@AuraEnabled(cacheable=true)
public static List<Book__c> getBooks() {
    return [
        SELECT Id, Name, Title__c, Author__c, Category__c, Availability_Status__c
        FROM Book__c
        ORDER BY Name
    ];
}

// ------------------- GET MEMBERS -------------------
@AuraEnabled(cacheable=true)
public static List<Member__c> getMembers() {
    return [
        SELECT Id, Name, Member_Name__c, Membership_Type__c, Status__c, Borrow_Count__c
        FROM Member__c
        ORDER BY Name
    ];
}

// ------------------- GET AVAILABLE BOOKS -------------------
@AuraEnabled(cacheable=true)
public static List<Book__c> getAvailableBooks() {
    return [
        SELECT Id, Name
        FROM Book__c
        WHERE Availability_Status__c = 'Available'
        ORDER BY Name
    ];
}

// ------------------- BORROW BOOK -------------------
@AuraEnabled
public static void createBorrowRecord(Id memberId, Id bookId)
{
    try {

        if(memberId == null || bookId == null){
            throw new AuraHandledException('Member and Book are required');
        }

        Book__c book = [
            SELECT Id, Availability_Status__c
            FROM Book__c
            WHERE Id = :bookId
            LIMIT 1
        ];

        if(book.Availability_Status__c == null ||
           !book.Availability_Status__c.equalsIgnoreCase('Available')){
            throw new AuraHandledException('Book is not available');
        }

        Borrowing_Record__c borrow = new Borrowing_Record__c(
            Member__c = memberId,
            Book__c = bookId,
            Borrow_Date__c = Date.today(),
            Due_Date__c = Date.today().addDays(7),
            Borrow_Status__c = 'Borrowed',
            Is_Returned__c = false
        );

        insert borrow;

        // ✅ Use correct picklist value
        book.Availability_Status__c = 'Borrowed';
        update book;

    } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
    }
}

// ------------------- RETURN BOOK -------------------
@AuraEnabled
public static void returnBook(Id borrowId)
{
    Borrowing_Record__c borrow = [
        SELECT Id, Book__c
        FROM Borrowing_Record__c
        WHERE Id = :borrowId
        LIMIT 1
    ];

    borrow.Borrow_Status__c = 'Returned';
    borrow.Is_Returned__c = true;
    update borrow;

    // Make Book Available Again
    Book__c book = [
        SELECT Id, Availability_Status__c
        FROM Book__c
        WHERE Id = :borrow.Book__c
        LIMIT 1
    ];

    book.Availability_Status__c = 'Available';
    update book;
}

// ------------------- ACTIVE BORROWS -------------------
@AuraEnabled(cacheable=true)
public static List<Borrowing_Record__c> getActiveBorrows(Id memberId){

    if(memberId == null){
        return new List<Borrowing_Record__c>();
    }

    return [
        SELECT Id,
               Name,
               Borrow_Date__c,
               Due_Date__c,
               Borrow_Status__c,
               Book__r.Name,
               Book__r.Title__c,
               Book__r.Author__c
        FROM Borrowing_Record__c
        WHERE Member__c = :memberId
        AND Borrow_Status__c = 'Borrowed'
        ORDER BY Borrow_Date__c DESC
    ];
}


}