force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Book Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/Borrowing_Record__c.object-meta.xml
<CustomObject>
    <label>Borrowing Record</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Borrowing Record id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Status__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Status__c</fullName>
    <label>Borrow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookStatusAvailableHandler.cls
public with sharing class BookStatusAvailableHandler {

    public static void BookStatusAvailableHandler(List<Borrowing_Record__c> newBorrowList, Map<Id, Borrowing_Record__c> oldMap) 
    {
        set<Id> booksToMakeAvailable = new set<Id>();

        for(Borrowing_Record__c br : newBorrowList)
        {
            Borrowing_Record__c oldBr = oldMap.get(br.Id);
            if(oldBr.return_date__c == null && br.return_date__c != null)
            {
                booksToMakeAvailable.add(br.Book__c);
            }
        }

        updateBooks(booksToMakeAvailable, 'Available');
    }


    public static void updateBooks(set<Id> bookIds, String status)
    {
        if(bookIds.isEmpty())
            return;

        List<Book__c> booksToUpdate = [SELECT Id, Availability_Status__c FROM Book__c WHERE Id IN :bookIds];
        
        for(Book__c b : booksToUpdate)
        {
            b.Availability_Status__c = status;
        }

        update booksToUpdate;
    }

    public static void updateBorrowStatus(List<Borrowing_Record__c> borrowList)
    {
        for(Borrowing_Record__c br : borrowList)
        {
            br.Borrow_Status__c = 'Returned';
        }
    }
}