force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Book Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Availability_Status__c.field-meta.xml
<CustomField>
    <fullName>Availability_Status__c</fullName>
    <label>Availability Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/Borrowing_Record__c.object-meta.xml
<CustomObject>
    <label>Borrowing Record</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Borrowing Record id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Date__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Date__c</fullName>
    <label>Borrow Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Status__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Status__c</fullName>
    <label>Borrow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Borrow_Count__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Count__c</fullName>
    <label>Borrow Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LibraryApexTestClass.cls
@isTest
public with sharing class LibraryApexTestClass 
{
    @TestSetup
    public static void setUpData(){
        
        Member__c member = new Member__c( Borrow_Count__c = 0);
        insert member;

        Book__c book = new Book__c(Availability_Status__c = 'Available');
        insert book;
    }

    //Scenerio 1: Test Book status Update
    @isTest
    public static void testBookStatusAvailableHandler() 
    {   
        Member__c member = [select id from Member__c limit 1];
        Book__c book = [select id from Book__c limit 1];

        Borrowing_Record__c borrow = new Borrowing_Record__c(Member__c = member.Id, Book__c = book.Id, Borrow_Date__c = Date.today()-10, Due_Date__c = Date.today()-3, Borrow_Status__c = 'Borrowed');
        insert borrow;

        book__c updateBookStatus = [select Availability_Status__c from Book__c where id = :book.id];
        
        System.assertEquals('Borrowed', updateBookStatus.Availability_Status__c);

       borrow.Borrow_Status__c = 'Returned';
        update borrow;

// Re-query to confirm
            Borrowing_Record__c updatedBorrow =
            [SELECT Borrow_Status__c 
            FROM Borrowing_Record__c 
            WHERE Id = :borrow.Id];

System.assertEquals('Returned', updatedBorrow.Borrow_Status__c);


        updateBookStatus = [select Availability_Status__c from Book__c where id = :book.id];

        System.assertEquals('Available', updateBookStatus.Availability_Status__c);
        
    }

    //Scenerio 2: Test Prevent Book Deletion
    @isTest
    public static void testPreventBookDeleteHandler()
    {
        Member__c member = [select id from Member__c limit 1];
        Book__c book = [select id from Book__c limit 1];


        Borrowing_Record__c borrow = new Borrowing_Record__c(Member__c = member.Id, Book__c = book.Id, Borrow_Date__c = Date.today()-10, Due_Date__c = Date.today()-3, Borrow_Status__c = 'Borrowed');
        insert borrow;

        Test.startTest();
        try{
            delete book;
            System.assert(false);
        }catch(Exception e){
            System.assert(e.getMessage().contains('Cannot delete book as it is currently borrowed'));
        }
        Test.stopTest();



    }

    //Scenerio 3: Test Prevent Member Deletion
    @isTest
    public static void testPreventMemberDeletionHandler()
    {
        Member__c member = [select id from Member__c limit 1];
        Book__c book = [select id from Book__c limit 1];

        Borrowing_Record__c borrow = new Borrowing_Record__c(Member__c = member.Id, Book__c = book.Id, Borrow_Date__c = Date.today()-10, Due_Date__c = Date.today()-3, Borrow_Status__c = 'Borrowed');
        insert borrow;

        Test.startTest();
        try{
            delete member;
            System.assert(false);
        }catch(Exception e){
             System.assert(e.getMessage().contains('Cannot delete member with active borrowing records'));
        }
        Test.stopTest();
    }





}