force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Book Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/Borrowing_Record__c.object-meta.xml
<CustomObject>
    <label>Borrowing Record</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Borrowing Record id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Book_Title__c.field-meta.xml
<CustomField>
    <fullName>Book_Title__c</fullName>
    <description>Title Of related Book</description>
    <label>Book Title</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Date__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Date__c</fullName>
    <label>Borrow Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Status__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Status__c</fullName>
    <label>Borrow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Due_date__c.field-meta.xml
<CustomField>
    <fullName>Due_date__c</fullName>
    <label>Due date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <description>Related Member Name</description>
    <label>Member Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Borrow_Count__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Count__c</fullName>
    <label>Borrow Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <label>Member Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Librarian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Reservation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Book_Title__c.field-meta.xml
<CustomField>
    <fullName>Book_Title__c</fullName>
    <description>Related Book Name</description>
    <label>Book Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/memberProfileController.cls
public with sharing class memberProfileController {

    @AuraEnabled(cacheable=true)
public static Map<String, Object> getLoggedInMemberPhoto() {

    Id userId = UserInfo.getUserId();

    Member__c member = [
        SELECT Id,
               Name,
               Member_Name__c,
               Email__c,
               Phone__c,
               Status__c,
               Borrow_Count__c,
               Membership_Type__c
               
        FROM Member__c
        WHERE User__c = :userId
        LIMIT 1
    ];

    User u = [
        SELECT FullPhotoUrl
        FROM User
        WHERE Id = :userId
    ];

    return new Map<String, Object>{
        'member' => member,
        'photoUrl' => u.FullPhotoUrl
    };
}



@AuraEnabled(cacheable=true)
public static Map<String, Integer> getMemberSummary() {

    Id userId = UserInfo.getUserId();

    Member__c member = [
        SELECT Id
        FROM Member__c
        WHERE User__c = :userId
        LIMIT 1
    ];

    Map<String, Integer> summary = new Map<String, Integer>();

    summary.put('borrowed', [
        SELECT COUNT()
        FROM Borrowing_Record__c
        WHERE Member__c = :member.Id
        AND Borrow_Status__c = 'Borrowed'
    ]);

    summary.put('overdue', [
        SELECT COUNT()
        FROM Borrowing_Record__c
        WHERE Member__c = :member.Id
        AND Borrow_Status__c = 'Overdue'
    ]);

    summary.put('reserved', [
        SELECT COUNT()
        FROM Reservation__c
        WHERE Member__c = :member.Id
    ]);

    summary.put('returned', [
        SELECT COUNT()
        FROM Borrowing_Record__c
        WHERE Member__c = :member.Id
        AND Borrow_Status__c = 'Returned'
    ]);

    return summary;
}


@AuraEnabled(cacheable=true)
public static List<Borrowing_Record__c> getRecentBorrowedBooks() {

    Id userId = UserInfo.getUserId();

    Member__c member = [
        SELECT Id
        FROM Member__c
        WHERE User__c = :userId
        LIMIT 1
    ];

    return [
        SELECT Id,
               Book__r.Name,
               Book_Title__c,
               Borrow_Date__c,
               Due_date__c,
               Borrow_Status__c
        FROM Borrowing_Record__c
        WHERE Member__c = :member.Id
        ORDER BY CreatedDate DESC
        LIMIT 5
    ];
}

}