force-app/main/default/objects/Borrowing_Record__c/Borrowing_Record__c.object-meta.xml
<CustomObject>
    <label>Borrowing Record</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Borrowing Record id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowing Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing_Record__c/fields/Borrow_Status__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Status__c</fullName>
    <label>Borrow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrowed</fullName>
                <default>true</default>
                <label>Borrowed</label>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Member</label>
    <referenceTo>Member__c</referenceTo>
    <relationshipLabel>Borrowing Records</relationshipLabel>
    <relationshipName>Borrowing_Records</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing_Record__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <description>Related Member Name</description>
    <label>Member Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Member__c/Member__c.object-meta.xml
<CustomObject>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Member__c/fields/Borrow_Count__c.field-meta.xml
<CustomField>
    <fullName>Borrow_Count__c</fullName>
    <label>Borrow Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Member__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <label>Member Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MemberController.cls
public with sharing class MemberController {

    @AuraEnabled(cacheable=true)
    public static Integer getTotalMembers() {
        return [SELECT COUNT() FROM Member__c];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getActiveMembers() {
        return [
            SELECT COUNT()
            FROM Member__c
            WHERE Status__c = 'Active'
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getInactiveMembers() {
        return [
            SELECT COUNT()
            FROM Member__c
            WHERE Status__c = 'Inactive'
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getBorrowingMembers() {

        AggregateResult ar = [
            SELECT COUNT_DISTINCT(Member__c) total
            FROM Borrowing_Record__c
            WHERE Borrow_Status__c = 'Borrowed'
        ];

    return (Integer) ar.get('total');
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Member__c> getMemberTable() {
        return [
            SELECT Id,
                   Name,
                   Member_Name__c,
                   Email__c,
                   Phone__c,
                   Borrow_Count__c,
                   Status__c
            FROM Member__c
        ];
    }

    @AuraEnabled
    public static void deleteMember(Id memberId) {
        delete [SELECT Id FROM Member__c WHERE Id = :memberId];
    }
}